import type { Metadata } from 'next';
import { Inter, Manrope } from 'next/font/google';
import './globals.css';

const interFont = Inter({
    subsets: ['latin', 'cyrillic'],
    variable: '--font-inter',
    weight: ['400', '700', '900']
});
const manropeFont = Manrope({
    subsets: ['latin', 'cyrillic'],
    variable: '--font-manrope',
    weight: ['400', '700']
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${interFont.variable} ${manropeFont.variable} bg-background py-[33px] lg:px-[120px]`}>
                {children}
            </body>
        </html>
    );
}
